/* ------------AUTH CONTEXT------------- */
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

/* ------------MOVIE CONTEXT------------- */
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const CREATE_MOVIES_START = 'CREATE_MOVIES_START';
export const CREATE_MOVIES_SUCCESS = 'CREATE_MOVIES_SUCCESS';
export const CREATE_MOVIES_FAILURE = 'CREATE_MOVIES_FAILURE';

export const UPDATE_MOVIES_START = 'UPDATE_MOVIES_START';
export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS';
export const UPDATE_MOVIES_FAILURE = 'UPDATE_MOVIES_FAILURE';

export const DELETE_MOVIES_START = 'DELETE_MOVIES_START';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE';

/* ------------LIST CONTEXT------------- */
export const GET_LISTS_START = 'GET_LISTS_START';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';

export const CREATE_LISTS_START = 'CREATE_LISTS_START';
export const CREATE_LISTS_SUCCESS = 'CREATE_LISTS_SUCCESS';
export const CREATE_LISTS_FAILURE = 'CREATE_LISTS_FAILURE';

export const UPDATE_LISTS_START = 'UPDATE_LISTS_START';
export const UPDATE_LISTS_SUCCESS = 'UPDATE_LISTS_SUCCESS';
export const UPDATE_LISTS_FAILURE = 'UPDATE_LISTS_FAILURE';

export const DELETE_LISTS_START = 'DELETE_LISTS_START';
export const DELETE_LISTS_SUCCESS = 'DELETE_LISTS_SUCCESS';
export const DELETE_LISTS_FAILURE = 'DELETE_LISTS_FAILURE';
