/* ------------AUTH CONTEXT------------- */
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

/* ------------MOVIE CONTEXT------------- */
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const CREATE_MOVIES_START = 'CREATE_MOVIES_START';
export const CREATE_MOVIES_SUCCESS = 'CREATE_MOVIES_SUCCESS';
export const CREATE_MOVIES_FAILURE = 'CREATE_MOVIES_FAILURE';

export const UPDATE_MOVIES_START = 'UPDATE_MOVIES_START';
export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS';
export const UPDATE_MOVIES_FAILURE = 'UPDATE_MOVIES_FAILURE';

export const DELETE_MOVIES_START = 'DELETE_MOVIES_START';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE';
